//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mts.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public decimal Price { get; set; }
        public string ModelName { get; set; }
        public string Description { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
